# name: Waka Readme

# on:
#   workflow_dispatch: # Allows manual workflow trigger
#   schedule:
#     - cron: '0 0 * * *' # Runs at midnight UTC

# jobs:
#   update-readme:
#     name: WakaReadme DevMetrics
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2 # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it
#       - uses: athul/waka-readme@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # Uses your WakaTime API Key from your secrets
#           TIME_RANGE: all_time # Specifies the time range for WakaTime data
#           BLOCKS: '░▒▓█' # Customizes the graph blocks in the WakaTime stats
#           SHOW_TITLE: true # Shows the title for the WakaTime stats section
#           SHOW_TOTAL: true # Shows the total coding time
#           LANG_COUNT: 8 # Specifies the number of languages to display
#           REPOSITORY: Paing-Ko/Paing-Ko # Specify the target repository for the README update
#           # Uncomment the following lines if you're not updating a profile README
#           #GH_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub token for committing changes
